=== apache/xalan-c/xalan/c/trunk/xdocs/style/csv/book.dtd
<?xml encoding='US-ASCII'?>

<!-- STYLEBOOK BOOK DTD -->

<!-- import the external source-specific dtd -->
<!ENTITY % externalEntity SYSTEM "../../sources/entities.ent">
%externalEntity;

<!ELEMENT book (resources?|document|hidden|faqs|changes|group|external|separator)+>
<!ATTLIST book title     CDATA #REQUIRED
               copyright CDATA #IMPLIED>
               
<!ELEMENT resources EMPTY>
<!ATTLIST resources source CDATA #REQUIRED>

<!ELEMENT document EMPTY>
<!ATTLIST document id     ID    #REQUIRED
                   source CDATA #REQUIRED
                   label  CDATA #REQUIRED>

<!ELEMENT hidden EMPTY>
<!ATTLIST hidden id     ID    #REQUIRED
                 source CDATA #REQUIRED>

<!ELEMENT faqs EMPTY>
<!ATTLIST faqs id     ID    #REQUIRED
               source CDATA #REQUIRED
               label  CDATA #REQUIRED>

<!ELEMENT changes EMPTY>
<!ATTLIST changes id     ID    #REQUIRED
                  source CDATA #REQUIRED
                  label  CDATA #REQUIRED>

<!-- (entry) not supported in markup, cannot be tested -->
<!-- (group) not to have entry children, only standard children -->
<!-- <!ELEMENT group (entry)+> -->

<!ELEMENT group (document|faqs|changes|external)*> 
<!ATTLIST group id    ID    #IMPLIED
                label CDATA #REQUIRED>

<!-- (entry) not supported in markup, cannot be tested
<!ELEMENT entry EMPTY>
<!ATTLIST entry id     ID    #REQUIRED
                source CDATA #REQUIRED>
-->

<!ELEMENT external EMPTY>
<!ATTLIST external label CDATA #REQUIRED
                   href  CDATA #REQUIRED>
                   
<!ELEMENT separator EMPTY>

<!-- CVS $Revision: 1.3 $ $Date: 1999/12/01 23:03:37 $ -->
<!-- Revision by (shathaway@apache.org) 2011/09/01 -->

=== apache/xalan-c/xalan/java/trunk/xdocs/sources/xalan-apache-org-site.xml
<?xml version="1.0"?>
<!DOCTYPE book SYSTEM "../style/dtd/book.dtd">

<!--
 * Copyright 2000-2012 The Apache Software Foundation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
-->

<book title="Apache Xalan Project " copyright="2011 The Apache Software Foundation">
  <document id="index" label="Apache Xalan" source="xalan-apache-org/index.xml"/>
  <document id="charter" label="Charter" source="xalan-apache-org/charter.xml"/>
  <separator/>  
<!--
  <external href="http://xml.apache.org/xalan-c" label="Xalan C++"/>  
  <external href="http://xml.apache.org/xalan-j" label="Xalan Java 2"/>
-->
<group label="Projects">
  <external href="xalan-c/index.html" label="Xalan C++"/>  
  <external href="xalan-j/index.html" label="Xalan Java 2"/>
</group>
  <separator/>  
<group label="Mail Lists">
  <external href="http://marc.theaimsgroup.com/?l=xalan-dev " label="Developers Archive"/>
  <external href="http://marc.theaimsgroup.com/?l=xalan-c-users" label="C Users Archive"/>
  <external href="http://marc.theaimsgroup.com/?l=xalan-j-users" label="J Users Archive"/>
</group>
  <separator/>
<group label="Resources">
  <external href="http://www.apache.org/" label="Apache"/>
  <external href="http://www.apache.org/foundation/getinvolved.html" label="Get Involved"/>
  <external href="http://www.apache.org/licenses/" label="Licenses"/>
  <external href="http://www.apache.org/foundation/sponsorship.html" label="Sponsorship"/>
  <external href="http://www.apache.org/foundation/thanks.html" label="Thanks"/>
  <external href="http://www.apache.org/security/" label="Security"/>
</group>
  <separator/>
</book>

=== apache/xalan-c/xalan/c/trunk/xdocs/sources/docs/book.xml
<?xml version="1.0"?>
<!DOCTYPE book SYSTEM "../../style/dtd/book.dtd">

<book title="Test Documentation" copyright="1999 Apache Software Foundation">
  <document id="readme"     label="Readme"     source="readme.xml"    />
  <document id="sections"   label="Sections"   source="sections.xml"  />
  <separator                                                          />
  <document id="blocks"     label="Blocks"     source="blocks.xml"    />
  <document id="characters" label="Characters" source="characters.xml"/>
  <document id="links"      label="Links"      source="links.xml"     />
  <separator                                                          />
  <faqs     id="faqs"       label="FAQ File"   source="faqs.xml"      />
<hidden>
  <group    id="faqgroup"   label="FAQ Group"                          >
    <entry  id="faqs-1"                        source="faqs-1.xml"    />
    <entry  id="faqs-2"                        source="faqs-2.xml"    />
  </group                                                              >    
</hidden>
  <changes  id="changes"    label="Changes"    source="changes.xml"   />
</book>
